//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomakuRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblT_Roomaku
    {
        public long ID { get; set; }
        public string Nama { get; set; }
        public string Lokasi { get; set; }
        public string Telp { get; set; }
        public string Email { get; set; }
        public string Material { get; set; }
    }
}
